//! The S4 wire seam (spike memo Q3, decision 2): every state-machine
//! step of the authentication adapter driven hermetically through the
//! REAL Muon hyper transport against a hand-written std HTTP/1.1
//! responder on loopback, pointed at by a custom `Environment`
//! (`Scheme::Http` skips TLS). The login steps run a REAL SRP exchange
//! in both directions: the client proof is generated by pinned
//! `proton-srp` client code and verified by a real `proton-srp` server
//! interaction (muon's own SRP implementation, driving the same
//! verifier the scripted API would store), and the server proof it
//! returns is verified by the client — no canned SRP bytes anywhere.
//!
//! Recorded limit (spike memo Q3): DoH-based indirect resolution cannot
//! be loopback-faked, so alternative-routing coverage exercises the
//! direct-class multi-server partition (`find_available_sender`'s
//! ordering across a dead and a live direct server) — the same code
//! path AR uses. DoH/indirect resolution and TLS pinning have no
//! automated offline coverage; tracked for a pre-release networked arm
//! (the canary arm below is direct-only too).
//!
//! The canary arm at the bottom is the S1 harness's real-muon emitter
//! (m2-plan S1/S4): muon's REAL auth code paths driven offline with the
//! canary values as live credentials, asserted through
//! `protonwire_core::redact::canary::assert_no_secrets_reach_logs`
//! unchanged.

use std::io::Read as _;
use std::io::Write as _;
use std::net::TcpListener;
use std::net::TcpStream;
use std::sync::Arc;
use std::sync::Mutex;
use std::sync::OnceLock;
use std::time::Duration;
use std::time::Instant;

use serde_json::Value;
use serde_json::json;

use protonwire_api::AuthenticationApi as _;
use protonwire_api::Fido2Challenge;
use protonwire_api::Fido2Payload;
use protonwire_api::ForkSelector;
use protonwire_api::LoginStatus;
use protonwire_api::LoginStep;
use protonwire_api::auth::MemorySessionStore;
use protonwire_api::auth::MuonAuth;
use protonwire_api::runtime::EngineBridge as _;
use protonwire_api::runtime::TokioBridge;

// ===========================================================================
// The std HTTP/1.1 responder with scripted, computable responses
// ===========================================================================

/// One recorded request.
#[derive(Debug, Clone)]
struct Recorded {
    method: String,
    path: String,
    headers: Vec<(String, String)>,
    body: Vec<u8>,
}

impl Recorded {
    fn header(&self, name: &str) -> Option<&str> {
        let name = name.to_ascii_lowercase();
        self.headers
            .iter()
            .find(|(k, _)| *k == name)
            .map(|(_, v)| v.as_str())
    }

    fn json(&self) -> Value {
        serde_json::from_slice(&self.body).expect("recorded body is JSON")
    }
}

/// One scripted response.
struct Response {
    status: &'static str,
    headers: Vec<(String, String)>,
    body: Vec<u8>,
}

impl Response {
    fn json(status: &'static str, body: Value) -> Self {
        Self {
            status,
            headers: vec![("Content-Type".into(), "application/json".into())],
            body: serde_json::to_vec(&body).expect("serialize scripted body"),
        }
    }

    fn error(status: &'static str, code: u16, message: &str) -> Self {
        Self::json(status, json!({"Code": code, "Error": message}))
    }

    fn empty(status: &'static str) -> Self {
        Self {
            status,
            headers: Vec::new(),
            body: Vec::new(),
        }
    }
}

/// One exchange: serve `respond(&recorded)` for the request matching
/// `method`/`path` (the responder serves steps strictly in order and
/// asserts each request matches its step).
struct Step {
    method: &'static str,
    path: String,
    respond: Box<dyn Fn(&Recorded) -> Response + Send>,
}

impl Step {
    fn static_json(
        method: &'static str,
        path: impl Into<String>,
        status: &'static str,
        body: Value,
    ) -> Self {
        Self {
            method,
            path: path.into(),
            respond: Box::new(move |_| Response::json(status, body.clone())),
        }
    }

    fn computed(
        method: &'static str,
        path: impl Into<String>,
        respond: impl Fn(&Recorded) -> Response + Send + 'static,
    ) -> Self {
        Self {
            method,
            path: path.into(),
            respond: Box::new(respond),
        }
    }
}

/// Serves the script sequentially over KEEP-ALIVE connections: the
/// client's whole exchange (anonymous-session mint, SRP handshake, 2FA,
/// ...) rides the one pooled HTTP/1.1 connection Muon's pool maintains —
/// exactly how the real API is spoken. A new connection is accepted
/// only when the client opens one (e.g. a resend after a scripted
/// error). Bounded waits so an unexpected stall fails the test instead
/// of hanging it.
///
/// (Why not `Connection: close` per exchange, the way a naive responder
/// does it: closing under Muon's pooled sender triggers its
/// channel-closed retry path, whose redial stalls under the sync
/// adapter's foreign-thread `block_on` drive — observed as a 30 s
/// timeout with the retry connecting only at teardown. Keeping the
/// pooled connection alive avoids that path entirely and matches the
/// production wire.)
fn spawn_scripted(
    steps: Vec<Step>,
) -> (std::thread::JoinHandle<()>, u16, Arc<Mutex<Vec<Recorded>>>) {
    const ACCEPT_TIMEOUT: Duration = Duration::from_secs(30);
    const IO_TIMEOUT: Duration = Duration::from_secs(30);

    let listener = TcpListener::bind("127.0.0.1:0").expect("bind loopback");
    let port = listener.local_addr().unwrap().port();
    let recorded = Arc::new(Mutex::new(Vec::new()));
    let seen = Arc::clone(&recorded);
    let handle = std::thread::spawn(move || {
        listener
            .set_nonblocking(true)
            .expect("responder nonblocking");
        let mut steps = steps.into_iter().peekable();
        'script: loop {
            if steps.peek().is_none() {
                break 'script;
            }
            // Wait for a connection (bounded poll; the client may still
            // be on the previous one, so this is not the only path).
            let waited = Instant::now();
            let mut stream = 'accept: loop {
                match listener.accept() {
                    Ok((stream, _)) => break 'accept stream,
                    Err(e) if e.kind() == std::io::ErrorKind::WouldBlock => {
                        if waited.elapsed() > ACCEPT_TIMEOUT {
                            break 'script;
                        }
                        std::thread::sleep(Duration::from_millis(5));
                    }
                    Err(e) => panic!("responder accept failed: {e}"),
                }
            };
            stream.set_nonblocking(false).expect("blocking stream");
            stream.set_read_timeout(Some(IO_TIMEOUT)).unwrap();
            stream.set_write_timeout(Some(IO_TIMEOUT)).unwrap();
            // Serve as many steps as the client pipelines onto this
            // connection; close when it closes or a read times out.
            while steps.peek().is_some() {
                let step = steps.next().expect("peeked");
                match read_request(&mut stream) {
                    Ok(recorded) => serve_exchange(&mut stream, step, recorded, &seen),
                    Err(e) if e.kind() == std::io::ErrorKind::WouldBlock => break,
                    Err(e) if e.kind() == std::io::ErrorKind::UnexpectedEof => break,
                    Err(e) => panic!("responder read failed: {e}"),
                }
            }
        }
    });
    (handle, port, recorded)
}

/// Reads one request (headers + Content-Length body) from the live
/// connection.
fn read_request(stream: &mut TcpStream) -> std::io::Result<Recorded> {
    let mut buf: Vec<u8> = Vec::with_capacity(1024);
    let mut chunk = [0u8; 8192];
    let header_end;
    loop {
        if let Some(pos) = find_terminator(&buf) {
            header_end = pos;
            break;
        }
        let n = stream.read(&mut chunk)?;
        if n == 0 {
            return Err(std::io::Error::new(
                std::io::ErrorKind::UnexpectedEof,
                "connection closed between requests",
            ));
        }
        buf.extend_from_slice(&chunk[..n]);
    }
    let head = String::from_utf8_lossy(&buf[..header_end]).into_owned();
    let mut lines = head.split("\r\n");
    let request_line = lines.next().unwrap_or_default().to_owned();
    let (method, path) = match request_line.split_once(' ') {
        Some((m, rest)) => (
            m.to_owned(),
            rest.split(' ').next().unwrap_or_default().to_owned(),
        ),
        None => (String::new(), String::new()),
    };
    let headers: Vec<(String, String)> = lines
        .filter_map(|line| line.split_once(':'))
        .map(|(k, v)| (k.to_ascii_lowercase(), v.trim().to_owned()))
        .collect();
    let content_length = headers
        .iter()
        .find(|(k, _)| k == "content-length")
        .and_then(|(_, v)| v.parse::<usize>().ok())
        .unwrap_or(0);
    let mut body = buf[header_end..].to_vec();
    while body.len() < content_length {
        let n = stream.read(&mut chunk)?;
        if n == 0 {
            break;
        }
        body.extend_from_slice(&chunk[..n]);
    }
    body.truncate(content_length);
    Ok(Recorded {
        method,
        path,
        headers,
        body,
    })
}

/// Serves one scripted response on the live keep-alive connection.
fn serve_exchange(
    stream: &mut TcpStream,
    step: Step,
    recorded: Recorded,
    seen: &Mutex<Vec<Recorded>>,
) {
    assert_eq!(
        recorded.method, step.method,
        "scripted step order: expected {} {}, got {} {}",
        step.method, step.path, recorded.method, recorded.path
    );
    assert_eq!(
        recorded.path, step.path,
        "scripted step order: expected {} {}",
        step.method, step.path
    );
    let response = (step.respond)(&recorded);
    seen.lock().unwrap().push(recorded);
    let mut out = format!(
        "HTTP/1.1 {}\r\nContent-Length: {}\r\n",
        response.status,
        response.body.len()
    );
    for (k, v) in &response.headers {
        out.push_str(&format!("{k}: {v}\r\n"));
    }
    out.push_str("\r\n");
    stream
        .write_all(out.as_bytes())
        .expect("responder write head");
    stream
        .write_all(&response.body)
        .expect("responder write body");
    stream.flush().expect("responder flush");
}

fn find_terminator(buf: &[u8]) -> Option<usize> {
    buf.windows(4).position(|w| w == b"\r\n\r\n").map(|p| p + 4)
}

// ===========================================================================
// The real SRP server half (proton-srp — muon's own SRP implementation)
// ===========================================================================

/// Proton's public signed SRP modulus, recorded verbatim from
/// `GET /auth/v4/modulus` (the same class of recorded fixture as the S6
/// catalog fixture). The pinned client verifies this PGP-signed message
/// against Proton's embedded key; a fabricated modulus would fail
/// verification, so the recorded one is load-bearing for a REAL exchange.
const MODULUS_RESPONSE: &str = include_str!("../testdata/signed_modulus.json");

fn signed_modulus() -> &'static str {
    static SIGNED: OnceLock<String> = OnceLock::new();
    SIGNED.get_or_init(|| {
        serde_json::from_str::<Value>(MODULUS_RESPONSE)
            .expect("recorded modulus fixture parses")
            .get("Modulus")
            .and_then(Value::as_str)
            .expect("Modulus field")
            .to_owned()
    })
}

/// Extracts the base64 modulus from the cleartext-signed PGP message
/// (payload between the armor headers, dash-escapes removed).
fn modulus_b64(signed: &str) -> String {
    let body = signed
        .split_once("\n\n")
        .expect("armored message header")
        .1
        .split("-----BEGIN PGP SIGNATURE")
        .next()
        .expect("signature block")
        .trim();
    body.lines()
        .map(|line| line.strip_prefix("- ").unwrap_or(line))
        .collect::<Vec<_>>()
        .join("")
}

/// A fresh 10-byte salt (b64), fixed per run: the verifier and the
/// scripted `/auth/v4/info` response must agree on it.
const SRP_SALT: &str = "Jl54BOeNTVl8Ng==";

/// The SRP server state for one scripted login: the verifier Proton
/// would store for the user, and the live server interaction issuing
/// challenges and verifying proofs.
struct SrpServer {
    interaction: Mutex<proton_srp::ServerInteraction>,
}

impl SrpServer {
    /// Registers `username`/`password` the way the API would: derive the
    /// verifier with the client-side helper over the same signed modulus
    /// and salt the scripted info response serves.
    fn register(username: &str, password: &str) -> Self {
        let verifier = proton_srp::SRPAuth::generate_verifier(
            &proton_srp::RPGPVerifier::default(),
            password,
            Some(SRP_SALT),
            signed_modulus(),
        )
        .expect("generate SRP verifier");
        assert_eq!(verifier.version, proton_srp::PROTON_SRP_VERSION);
        let verifier_b64 = proton_srp::SRPVerifierB64::from(verifier).verifier;
        let raw_modulus = proton_srp::RawSRPModulus::new(&modulus_b64(signed_modulus()))
            .expect("recorded modulus is a valid 256-byte SRP modulus");
        let client_verifier =
            proton_srp::ServerClientVerifier::new(&verifier_b64).expect("verifier shape");
        let interaction = proton_srp::ServerInteraction::new(&raw_modulus, &client_verifier)
            .expect("server interaction");
        let _ = username;
        Self {
            interaction: Mutex::new(interaction),
        }
    }

    /// `/auth/v4/info`: issue the server ephemeral.
    fn challenge(&self) -> String {
        self.interaction
            .lock()
            .unwrap()
            .generate_challenge()
            .encode_b64()
    }

    /// `/auth/v4`: verify the client's proof; the server proof on
    /// success, `None` on a wrong password (the API answers 400).
    fn verify(&self, recorded: &Recorded) -> Option<String> {
        let body = recorded.json();
        let proof = proton_srp::ServerClientProof::new(
            body["ClientEphemeral"].as_str()?,
            body["ClientProof"].as_str()?,
        )
        .ok()?;
        self.interaction
            .lock()
            .unwrap()
            .verify_proof(&proof)
            .ok()
            .map(|proof| proof.encode_b64())
    }
}

// ===========================================================================
// Scripted response bodies (muon-rest wire shapes, spike memo Q1/Q2)
// ===========================================================================

const ANON_UID: &str = "anon-uid-0001";
const ANON_TOKEN: &str = "anon-token-0001";
const USER_UID: &str = "user-uid-0002";
const USER_ID: &str = "user-id-0003";
const ACCESS_TOKEN: &str = "access-token-0004";
const REFRESH_TOKEN: &str = "refresh-token-0005";

fn anon_session() -> Value {
    json!({
        "UID": ANON_UID,
        "UserID": null,
        "AccessToken": ANON_TOKEN,
        "RefreshToken": format!("{ANON_TOKEN}-refresh"),
        "Scopes": ["unauth"],
    })
}

fn auth_info(session_id: &str, ephemeral: String) -> Value {
    json!({
        "SRPSession": session_id,
        "Version": 4,
        "Salt": SRP_SALT,
        "Modulus": signed_modulus(),
        "ServerEphemeral": ephemeral,
    })
}

fn auth_v4(server_proof: String, scopes: &[&str], tfa: Value) -> Value {
    json!({
        "ServerProof": server_proof,
        "PasswordMode": 1,
        "UID": USER_UID,
        "UserID": USER_ID,
        "AccessToken": ACCESS_TOKEN,
        "RefreshToken": REFRESH_TOKEN,
        "Scopes": scopes,
        "2FA": tfa,
    })
}

fn tfa_none() -> Value {
    json!({"Enabled": 0})
}
fn tfa_totp() -> Value {
    json!({"Enabled": 1})
}

const FIDO_CHALLENGE_BYTES: [u8; 8] = [0xde, 0xad, 0xbe, 0xef, 1, 2, 3, 4];
const FIDO_CREDENTIAL_ID_BYTES: [u8; 4] = [9, 8, 7, 6];

fn tfa_fido() -> Value {
    json!({
        "Enabled": 2,
        "FIDO2": {
            "AuthenticationOptions": {
                "publicKey": {
                    "challenge": FIDO_CHALLENGE_BYTES.to_vec(),
                    "allowCredentials": [
                        {"type": "public-key", "id": FIDO_CREDENTIAL_ID_BYTES.to_vec()}
                    ],
                }
            },
            "RegisteredKeys": [
                {
                    "AttestationFormat": "packed",
                    "CredentialID": FIDO_CREDENTIAL_ID_BYTES.to_vec(),
                    "Name": "test-key",
                }
            ],
        }
    })
}

fn fido_options_json() -> Value {
    tfa_fido()["FIDO2"]["AuthenticationOptions"].clone()
}

fn refresh_response(new_access: &str, new_refresh: &str) -> Value {
    json!({
        "UID": USER_UID,
        "UserID": USER_ID,
        "AccessToken": new_access,
        "RefreshToken": new_refresh,
        "Scopes": ["loggedin", "full"],
    })
}

fn fork_get_response(uid: &str, user_id: &str) -> Value {
    json!({
        "Payload": null,
        "UID": uid,
        "UserID": user_id,
        "AccessToken": "fork-access-token",
        "RefreshToken": "fork-refresh-token",
        "Scopes": ["loggedin"],
    })
}

// ===========================================================================
// The loopback environment and the adapter harness
// ===========================================================================

/// The custom environment: direct-class loopback `http://` servers
/// (spike memo Q3 — `Scheme::Http` skips TLS).
#[derive(Debug, Clone)]
struct LoopbackEnv {
    servers: Vec<muon::common::Server>,
}

impl muon::env::Env for LoopbackEnv {
    fn servers(&self, _version: &muon::app::AppVersion) -> Vec<muon::common::Server> {
        self.servers.clone()
    }
    fn ar_pins(&self) -> Option<&muon::tls::pins::TlsPinSet> {
        None
    }
    fn api_pins(&self) -> Option<&muon::tls::pins::TlsPinSet> {
        None
    }
}

fn loopback_env(port: u16) -> muon::Environment {
    let server: muon::common::Server = format!("http://127.0.0.1:{port}/")
        .parse()
        .expect("loopback server url");
    muon::Environment::new_custom(LoopbackEnv {
        servers: vec![server],
    })
}

fn two_direct_servers_env(dead_port: u16, live_port: u16) -> muon::Environment {
    let servers: Vec<muon::common::Server> = [
        format!("http://127.0.0.1:{dead_port}/"),
        format!("http://127.0.0.1:{live_port}/"),
    ]
    .iter()
    .map(|url| url.parse().expect("loopback server url"))
    .collect();
    muon::Environment::new_custom(LoopbackEnv { servers })
}

fn adapter_against(env: muon::Environment) -> MuonAuth {
    let app = muon::App::new("linux-vpn@1.0.0").expect("app version");
    MuonAuth::connect(app, env, "protonwire").expect("adapter")
}

fn adapter_on_port(port: u16) -> MuonAuth {
    adapter_against(loopback_env(port))
}

/// A port nothing listens on.
fn dead_port() -> u16 {
    let listener = TcpListener::bind("127.0.0.1:0").unwrap();
    let port = listener.local_addr().unwrap().port();
    drop(listener);
    port
}

// ===========================================================================
// The scripted state-machine steps
// ===========================================================================

const USERNAME: &str = "visionary-user";
const PASSWORD: &str = "correct-horse-battery";

/// The login exchange with a REAL SRP server half: the same
/// `ServerInteraction` issues the `/auth/v4/info` challenge and verifies
/// the `/auth/v4` proof, exactly as the API would.
fn srp_login_steps(scopes: &'static [&'static str], tfa: Value) -> Vec<Step> {
    srp_login_steps_as(USERNAME, PASSWORD, scopes, tfa)
}

/// The login exchange for ARBITRARY credentials (the peer-secret pin
/// uses its own values so the SRP math is real for them too).
fn srp_login_steps_as(
    username: &str,
    password: &str,
    scopes: &'static [&'static str],
    tfa: Value,
) -> Vec<Step> {
    let server = Arc::new(SrpServer::register(username, password));
    let server_for_info = Arc::clone(&server);
    let server_for_auth = Arc::clone(&server);
    vec![
        // The anonymous-session mint muon performs before the first
        // send on a credential-less session (spike memo Q2).
        Step::static_json("POST", "/auth/v4/sessions", "200 OK", anon_session()),
        Step::computed("POST", "/auth/v4/info", move |_| {
            let ephemeral = server_for_info.challenge();
            Response::json("200 OK", auth_info("srp-session-1", ephemeral))
        }),
        Step::computed("POST", "/auth/v4", move |recorded| {
            match server_for_auth.verify(recorded) {
                Some(server_proof) => {
                    Response::json("200 OK", auth_v4(server_proof, scopes, tfa.clone()))
                }
                None => Response::error(
                    "400 Bad Request",
                    8002,
                    "incorrect password (real SRP proof verification failed)",
                ),
            }
        }),
    ]
}

fn two_factor_step() -> Step {
    Step::static_json(
        "POST",
        "/auth/v4/2fa",
        "200 OK",
        json!({"Scopes": ["loggedin", "full"]}),
    )
}

// ===========================================================================
// The wire tests
// ===========================================================================

/// SRP success end to end: the real client proof is generated by pinned
/// proton-srp, verified by the scripted API's real server interaction,
/// and the returned server proof is verified by the client — the only
/// way this step completes is a genuine SRP exchange. The trait object
/// coercion proves the adapter keeps the `&dyn` seam idiom.
#[test]
fn srp_login_success_round_trips_a_real_exchange() {
    let (handle, port, seen) = spawn_scripted(srp_login_steps(&["loggedin", "full"], tfa_none()));
    let adapter = adapter_on_port(port);

    let api: &dyn protonwire_api::AuthenticationApi = &adapter;
    let step = api.begin_login(USERNAME, PASSWORD).expect("login");
    handle.join().expect("responder thread");

    assert_eq!(
        step,
        LoginStep::Session(protonwire_api::SessionInfo {
            user_id: USER_ID.to_owned(),
            session_id: USER_UID.to_owned(),
        })
    );
    assert_eq!(api.login_status().unwrap(), LoginStatus::LoggedIn);

    let requests = seen.lock().unwrap();
    assert_eq!(
        requests
            .iter()
            .map(|r| (r.method.as_str(), r.path.as_str()))
            .collect::<Vec<_>>(),
        vec![
            ("POST", "/auth/v4/sessions"),
            ("POST", "/auth/v4/info"),
            ("POST", "/auth/v4"),
        ],
        "mint + SRP handshake order"
    );
    // The real transport's headers traveled: app version and the
    // minted anonymous bearer authorize the SRP sends.
    assert!(requests[2].header("x-pm-appversion").is_some());
    assert_eq!(
        requests[2].header("authorization"),
        Some("Bearer anon-token-0001"),
        "the minted anonymous session must authorize the auth send"
    );
    assert_eq!(requests[2].header("x-pm-uid"), Some(ANON_UID));
}

#[test]
fn fresh_adapter_reports_logged_out() {
    let (handle, port, _seen) = spawn_scripted(Vec::new());
    let adapter = adapter_on_port(port);
    handle.join().expect("responder thread");
    assert_eq!(adapter.login_status().unwrap(), LoginStatus::LoggedOut);
}

/// Wrong password: the REAL server-side proof verification fails, the
/// API answers 400, and the adapter surfaces a transport-class error
/// with the upstream detail (stable-code territory; never a panic).
#[test]
fn srp_wrong_password_fails_with_transport_error() {
    let (handle, port, _seen) = spawn_scripted(srp_login_steps(&["loggedin", "full"], tfa_none()));
    let adapter = adapter_on_port(port);

    let err = adapter
        .begin_login(USERNAME, "wrong-password")
        .expect_err("wrong password must fail");
    handle.join().expect("responder thread");

    match err {
        protonwire_api::ApiError::Transport(report) => assert!(!report.is_empty()),
        other => panic!("expected Transport failure, got {other:?}"),
    }
}

/// The 2FA challenge → TOTP round trip: the challenge descriptors are
/// Muon's typed `TFA`, reduced to the client-facing shape; the submitted
/// code travels as the `TwoFactorCode` arm; the completion reports the
/// identity the LOGIN flow observed (Muon's 2FA response carries scopes
/// only).
#[test]
fn two_factor_totp_round_trip() {
    let (handle, port, seen) = spawn_scripted(
        srp_login_steps(&["twofactor"], tfa_totp())
            .into_iter()
            .chain([two_factor_step()])
            .collect(),
    );
    let adapter = adapter_on_port(port);

    let step = adapter.begin_login(USERNAME, PASSWORD).expect("login");
    assert_eq!(
        step,
        LoginStep::Challenge(protonwire_api::Challenge {
            totp_enabled: true,
            fido2: None,
        })
    );
    let completed = adapter.submit_two_factor("123456").expect("2fa");
    handle.join().expect("responder thread");

    assert_eq!(
        completed,
        LoginStep::Session(protonwire_api::SessionInfo {
            user_id: USER_ID.to_owned(),
            session_id: USER_UID.to_owned(),
        })
    );
    assert_eq!(adapter.login_status().unwrap(), LoginStatus::LoggedIn);

    let requests = seen.lock().unwrap();
    let tfa_request = requests.last().expect("2fa request recorded");
    assert_eq!(tfa_request.path, "/auth/v4/2fa");
    assert_eq!(
        tfa_request.json()["TwoFactorCode"],
        "123456",
        "the TOTP arm must carry the code as TwoFactorCode"
    );
}

/// The 2FA challenge → FIDO2 round trip: the reduced challenge carries
/// the WebAuthn request options' challenge and allowed credentials; the
/// submitted assertion travels as the `FIDO2` arm with the ORIGINAL
/// `AuthenticationOptions` echoed (reconstructed by the adapter from the
/// challenge Muon delivered, not fabricated).
#[test]
fn two_factor_fido_round_trip() {
    let (handle, port, seen) = spawn_scripted(
        srp_login_steps(&["twofactor"], tfa_fido())
            .into_iter()
            .chain([two_factor_step()])
            .collect(),
    );
    let adapter = adapter_on_port(port);

    let step = adapter.begin_login(USERNAME, PASSWORD).expect("login");
    assert_eq!(
        step,
        LoginStep::Challenge(protonwire_api::Challenge {
            totp_enabled: false,
            fido2: Some(Fido2Challenge {
                challenge: FIDO_CHALLENGE_BYTES.to_vec(),
                allow_credentials: vec![FIDO_CREDENTIAL_ID_BYTES.to_vec()],
            }),
        })
    );

    let payload = Fido2Payload {
        client_data: "client-data-b64".into(),
        authenticator_data: "authenticator-data-b64".into(),
        signature: "signature-b64".into(),
        credential_id: FIDO_CREDENTIAL_ID_BYTES.to_vec(),
    };
    let completed = adapter.submit_fido_payload(&payload).expect("2fa fido");
    handle.join().expect("responder thread");

    assert_eq!(
        completed,
        LoginStep::Session(protonwire_api::SessionInfo {
            user_id: USER_ID.to_owned(),
            session_id: USER_UID.to_owned(),
        })
    );

    let requests = seen.lock().unwrap();
    let tfa_request = requests.last().expect("2fa request recorded");
    let body = tfa_request.json();
    assert_eq!(body["FIDO2"]["ClientData"], "client-data-b64");
    assert_eq!(body["FIDO2"]["AuthenticatorData"], "authenticator-data-b64");
    assert_eq!(body["FIDO2"]["Signature"], "signature-b64");
    assert_eq!(
        body["FIDO2"]["CredentialID"],
        json!(FIDO_CREDENTIAL_ID_BYTES)
    );
    assert_eq!(
        body["FIDO2"]["AuthenticationOptions"],
        fido_options_json(),
        "the original challenge options must be echoed, not fabricated"
    );
}

/// FR-7L fail-closed: a recovery-code-shaped second factor is refused
/// with the stable `unsupported-challenge` code BEFORE any wire action —
/// pinned muon has no recovery-code arm to send it through.
#[test]
fn recovery_code_input_fails_closed_without_wire_action() {
    let (handle, port, seen) = spawn_scripted(srp_login_steps(&["twofactor"], tfa_totp()));
    let adapter = adapter_on_port(port);

    let step = adapter.begin_login(USERNAME, PASSWORD).expect("login");
    assert!(matches!(step, LoginStep::Challenge(_)));
    let after_challenge = seen.lock().unwrap().len();

    match adapter.submit_two_factor("ABCD-EFGH") {
        Err(protonwire_api::ApiError::UnsupportedChallenge(code)) => {
            assert_eq!(code, "recovery-code");
        }
        other => panic!("expected UnsupportedChallenge, got {other:?}"),
    }
    handle.join().expect("responder thread");
    assert_eq!(
        seen.lock().unwrap().len(),
        after_challenge,
        "a fail-closed refusal must not touch the wire"
    );
}

/// A twofactor-scoped challenge offering neither TOTP nor FIDO2 cannot
/// be continued by pinned Muon: fail-closed `Blocked`, stable code.
#[test]
fn challenge_with_no_submittable_arm_blocks() {
    let (handle, port, _seen) = spawn_scripted(srp_login_steps(&["twofactor"], tfa_none()));
    let adapter = adapter_on_port(port);

    let step = adapter.begin_login(USERNAME, PASSWORD).expect("login");
    handle.join().expect("responder thread");
    assert_eq!(
        step,
        LoginStep::Blocked(protonwire_api::BlockedReason::UnsupportedChallenge)
    );
}

/// Second-factor submissions without a challenge in progress are state
/// refusals, never wire calls.
#[test]
fn submit_two_factor_without_a_challenge_is_a_state_refusal() {
    let (handle, port, seen) = spawn_scripted(Vec::new());
    let adapter = adapter_on_port(port);
    match adapter.submit_two_factor("123456") {
        Err(protonwire_api::ApiError::InvalidState(code)) => {
            assert_eq!(code, "no 2FA challenge in progress");
        }
        other => panic!("expected InvalidState, got {other:?}"),
    }
    handle.join().expect("responder thread");
    assert!(seen.lock().unwrap().is_empty(), "no wire action expected");
}

#[test]
fn fido_payload_without_a_fido_challenge_is_unsupported() {
    let (handle, port, _seen) = spawn_scripted(
        srp_login_steps(&["twofactor"], tfa_totp())
            .into_iter()
            .chain([two_factor_step()])
            .collect(),
    );
    let adapter = adapter_on_port(port);
    adapter.begin_login(USERNAME, PASSWORD).expect("login");
    match adapter.submit_fido_payload(&Fido2Payload {
        client_data: "x".into(),
        authenticator_data: "y".into(),
        signature: "z".into(),
        credential_id: vec![1],
    }) {
        Err(protonwire_api::ApiError::UnsupportedChallenge(code)) => {
            assert_eq!(code, "fido2-not-offered");
        }
        other => panic!("expected UnsupportedChallenge, got {other:?}"),
    }
    handle.join().expect("responder thread");
}

/// Forced refresh (`POST /auth/v4/refresh`) round trip: the refresh
/// token travels with the OAuth body, the new tokens land in the store,
/// and the reported status is `LoggedIn`.
#[test]
fn forced_refresh_swaps_the_tokens() {
    let (handle, port, seen) = spawn_scripted(
        srp_login_steps(&["loggedin", "full"], tfa_none())
            .into_iter()
            .chain([Step::static_json(
                "POST",
                "/auth/v4/refresh",
                "200 OK",
                refresh_response("access-token-NEW", "refresh-token-NEW"),
            )])
            .collect(),
    );
    let adapter = adapter_on_port(port);
    adapter.begin_login(USERNAME, PASSWORD).expect("login");

    assert_eq!(adapter.refresh().unwrap(), LoginStatus::LoggedIn);
    handle.join().expect("responder thread");

    match adapter.observed_credentials() {
        Some(credentials) => {
            assert_eq!(credentials.access_token(), "access-token-NEW");
            assert_eq!(credentials.refresh_token(), "refresh-token-NEW");
        }
        None => panic!("internal credentials must be observable after refresh"),
    }
    let requests = seen.lock().unwrap();
    let refresh = requests.last().expect("refresh recorded");
    let body = refresh.json();
    assert_eq!(body["GrantType"], "refresh_token");

    assert_eq!(body["RefreshToken"], REFRESH_TOKEN);
}

/// qa P2 (S4 review round): a 2FA submission after a forced refresh
/// must fail closed. `refresh()` used to leave `state.pending` in
/// place, so the STALE challenge — minted against pre-refresh session
/// material — drove the wire through `from_totp` as transport-class
/// nonsense. The decision (rust/qa converge): refresh invalidates the
/// pending challenge; the stale submit is an `InvalidState` refusal
/// with ZERO wire actions.
#[test]
fn submit_two_factor_after_refresh_is_a_state_refusal() {
    let (handle, port, seen) = spawn_scripted(
        srp_login_steps(&["twofactor"], tfa_totp())
            .into_iter()
            .chain([Step::static_json(
                "POST",
                "/auth/v4/refresh",
                "200 OK",
                refresh_response("access-token-NEW", "refresh-token-NEW"),
            )])
            .collect(),
    );
    let adapter = adapter_on_port(port);
    adapter.begin_login(USERNAME, PASSWORD).expect("login");
    adapter.refresh().expect("refresh");
    let before = seen.lock().unwrap().len();

    match adapter.submit_two_factor("123456") {
        Err(protonwire_api::ApiError::InvalidState(code)) => {
            assert_eq!(code, "no 2FA challenge in progress");
        }
        other => panic!("expected InvalidState, got {other:?}"),
    }
    handle.join().expect("responder thread");
    assert_eq!(
        seen.lock().unwrap().len(),
        before,
        "the stale submit must not touch the wire"
    );
}

/// Logout: the remote `DELETE /auth/v4` happens, local state always
/// clears, and the reported status is `LoggedOut` even though the
/// scripted DELETE response is empty.
#[test]
fn logout_clears_local_state() {
    let (handle, port, seen) = spawn_scripted(
        srp_login_steps(&["loggedin", "full"], tfa_none())
            .into_iter()
            .chain([Step::computed("DELETE", "/auth/v4", move |_| {
                Response::empty("200 OK")
            })])
            .collect(),
    );
    let adapter = adapter_on_port(port);
    adapter.begin_login(USERNAME, PASSWORD).expect("login");

    adapter.logout().expect("logout");
    handle.join().expect("responder thread");

    assert_eq!(adapter.login_status().unwrap(), LoginStatus::LoggedOut);
    let requests = seen.lock().unwrap();
    assert_eq!(requests.last().unwrap().method, "DELETE");
    assert_eq!(requests.last().unwrap().path, "/auth/v4");
}

/// Fork (`POST /auth/v4/sessions/forks`): the child identifier travels
/// as `ChildClientID`, the minted selector is returned, and — being a
/// locally-minted secret — it IS registered for scrubbing (FR-7P
/// layering; contrast the peer-secret pin below).
#[test]
fn fork_mints_a_child_selector() {
    let (handle, port, seen) = spawn_scripted(
        srp_login_steps(&["loggedin", "full"], tfa_none())
            .into_iter()
            .chain([Step::static_json(
                "POST",
                "/auth/v4/sessions/forks",
                "200 OK",
                json!({"Selector": "minted-selector-1"}),
            )])
            .collect(),
    );
    let adapter = adapter_on_port(port);
    adapter.begin_login(USERNAME, PASSWORD).expect("login");

    let selector = adapter.fork("localagent").expect("fork");
    handle.join().expect("responder thread");

    assert_eq!(selector.as_str(), "minted-selector-1");
    let requests = seen.lock().unwrap();
    let fork = requests.last().expect("fork recorded");
    let body = fork.json();
    assert_eq!(body["ChildClientID"], "localagent");
    // Local provenance: the minted value scrubs if ever formatted.
    assert_eq!(
        protonwire_core::redact::scrub("minted-selector-1"),
        protonwire_core::redact::REDACTED
    );
}

/// Fork while logged out is a state refusal, never a wire call.
#[test]
fn fork_logged_out_is_a_state_refusal() {
    let (handle, port, seen) = spawn_scripted(Vec::new());
    let adapter = adapter_on_port(port);
    match adapter.fork("localagent") {
        Err(protonwire_api::ApiError::InvalidState(code)) => assert_eq!(code, "not logged in"),
        other => panic!("expected InvalidState, got {other:?}"),
    }
    handle.join().expect("responder thread");
    assert!(seen.lock().unwrap().is_empty());
}

/// Fork import (`GET /auth/v4/sessions/forks/{selector}`, the FR-7L
/// external-session path): single-use selector consumed, no
/// anonymous-session mint (`no_unauth_session`), identity derived from
/// what Muon stored.
#[test]
fn import_fork_consumes_the_selector() {
    let selector_value = "imported-selector-9";
    let (handle, port, seen) = spawn_scripted(vec![Step::static_json(
        "GET",
        format!("/auth/v4/sessions/forks/{selector_value}"),
        "200 OK",
        fork_get_response("forked-uid-1", "forked-user-1"),
    )]);
    let adapter = adapter_on_port(port);

    let step = adapter
        .import_fork(&ForkSelector::new(selector_value))
        .expect("import");
    handle.join().expect("responder thread");

    assert_eq!(
        step,
        LoginStep::Session(protonwire_api::SessionInfo {
            user_id: "forked-user-1".to_owned(),
            session_id: "forked-uid-1".to_owned(),
        })
    );
    assert_eq!(adapter.login_status().unwrap(), LoginStatus::LoggedIn);

    let requests = seen.lock().unwrap();
    assert_eq!(requests.len(), 1, "no anonymous mint on the import path");
    assert!(requests[0].header("authorization").is_none());
}

/// Importing over an active session is a state refusal, never a wire
/// call — the client surfaces orchestrate logout → import.
#[test]
fn import_fork_over_an_active_session_refuses() {
    let (handle, port, seen) = spawn_scripted(srp_login_steps(&["loggedin", "full"], tfa_none()));
    let adapter = adapter_on_port(port);
    adapter.begin_login(USERNAME, PASSWORD).expect("login");
    let before = seen.lock().unwrap().len();

    match adapter.import_fork(&ForkSelector::new("some-selector")) {
        Err(protonwire_api::ApiError::InvalidState(code)) => {
            assert_eq!(code, "session active; logout before importing");
        }
        other => panic!("expected InvalidState, got {other:?}"),
    }
    handle.join().expect("responder thread");
    assert_eq!(seen.lock().unwrap().len(), before, "no wire action");
}

/// Transport failures surface as `ApiError::Transport` (never a panic,
/// never a fabricated session).
#[test]
fn transport_failures_map_to_transport_errors() {
    let adapter = adapter_on_port(dead_port());
    match adapter.begin_login(USERNAME, PASSWORD) {
        Err(protonwire_api::ApiError::Transport(report)) => assert!(!report.is_empty()),
        other => panic!("expected Transport failure, got {other:?}"),
    }
}

/// Alternative routing through the loopback seam (recorded limit,
/// spike memo Q3): TWO direct-class servers, the first dead — the
/// client's `find_available_sender` must exhaust the dead direct server
/// and proceed on the live one (the same direct/indirect partition path
/// AR rides). DoH resolution itself has no automated offline coverage —
/// see the recorded limit in this file's header (tracked: pre-release
/// networked arm).
#[test]
fn direct_class_servers_are_exhausted_in_order() {
    let (handle, live_port, seen) =
        spawn_scripted(srp_login_steps(&["loggedin", "full"], tfa_none()));
    let adapter = adapter_against(two_direct_servers_env(dead_port(), live_port));

    let step = adapter.begin_login(USERNAME, PASSWORD).expect("login");
    handle.join().expect("responder thread");
    assert!(matches!(step, LoginStep::Session(_)));
    assert_eq!(
        seen.lock().unwrap().len(),
        3,
        "the live server served the whole exchange after the dead first choice"
    );
}

/// FR-7JB resume + the NeedsRefresh arm: an adapter built over a store
/// preloaded with a refresh-only internal auth resumes the stored
/// session and reports `NeedsRefresh` (the S5 facade resumes exactly
/// this way after decrypting the envelope).
#[test]
fn preloaded_refresh_only_session_resumes_needing_refresh() {
    use muon::auth::Auth;
    use muon::auth::Tokens;
    use muon::store::Store as _;

    let (handle, port, _seen) = spawn_scripted(Vec::new());
    let mut store = MemorySessionStore::new();
    {
        let mut preloaded = store.get_all_auth();
        preloaded.insert(
            "protonwire".to_owned(),
            Auth::Internal {
                user_id: USER_ID.to_owned(),
                uid: USER_UID.to_owned(),
                tok: Tokens::Refresh {
                    ref_tok: "refresh-only".to_owned(),
                },
            },
        );
        store.set_all_auth(preloaded);
    }
    let app = muon::App::new("linux-vpn@1.0.0").expect("app version");
    let adapter = MuonAuth::build(
        app,
        loopback_env(port),
        "protonwire".to_owned(),
        TokioBridge::dedicated().expect("runtime"),
        store,
        muon::NoInfo,
    )
    .expect("adapter resumes the stored session");
    handle.join().expect("responder thread");

    assert_eq!(adapter.login_status().unwrap(), LoginStatus::NeedsRefresh);
}

/// FR-7C envelope bridge: the credentials this adapter observed
/// serialize EXACTLY into the store-side versioned envelope and
/// round-trip back into Muon's own type — the two crates provably
/// persist the same wire shape.
#[test]
fn observed_credentials_round_trip_through_the_session_envelope() {
    let (handle, port, _seen) = spawn_scripted(srp_login_steps(&["loggedin", "full"], tfa_none()));
    let adapter = adapter_on_port(port);
    adapter.begin_login(USERNAME, PASSWORD).expect("login");
    handle.join().expect("responder thread");

    let credentials = adapter
        .observed_credentials()
        .expect("internal credentials observed");
    let value = serde_json::to_value(&credentials).expect("muon serialization");
    let envelope = protonwire_store::session::SessionEnvelope::new(value).expect("envelope");

    let dir = TempDirGuard::new("envelope");
    let store =
        protonwire_store::session::SessionEnvelopeStore::new(dir.path().join("session.json"));
    store.save(&envelope).expect("persist");
    let loaded = store.load().expect("load").expect("present");

    let restored: muon::SessionCredentials =
        serde_json::from_value(loaded.credentials().clone()).expect("back into muon's type");
    assert_eq!(restored.access_token(), ACCESS_TOKEN);
    assert_eq!(restored.refresh_token(), REFRESH_TOKEN);
    assert_eq!(restored.uid(), USER_UID);
    assert_eq!(restored.user_id(), Some(USER_ID));
}

/// A per-test temp directory removed on drop (rust Low, S4 round: the
/// plain std fallback leaked a `pw-s4-envelope-*` directory per run —
/// panic-safe now too, which a trailing `remove_dir_all` call was not).
struct TempDirGuard(std::path::PathBuf);

impl TempDirGuard {
    fn new(tag: &str) -> Self {
        let dir = std::env::temp_dir().join(format!(
            "pw-s4-{tag}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        Self(dir)
    }

    fn path(&self) -> &std::path::Path {
        &self.0
    }
}

impl Drop for TempDirGuard {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

// ===========================================================================
// The peer-secret registry-blindness pin (S1's finding-10 gate)
// ===========================================================================

/// One mid-call scrub observation taken INSIDE a responder step
/// closure: (field label, the value checked, whether the global scrub
/// registry redacted it). Assertions happen on the TEST thread after
/// the exchange — a panic inside the responder thread would only
/// surface as an unrelated transport failure.
type ScrubObservation = (&'static str, String, bool);

/// Records a mid-call scrub check of `value`: scrubbing to anything
/// other than itself means the value was REGISTERED — exactly what the
/// peer-secret front door forbids for wire-supplied credentials. The
/// check runs while the adapter call is blocked on the response, the
/// one window a mutated registration's handle is provably live (the qa
/// M2/M4 survivors: post-call asserts run after the registry prunes a
/// dropped handle, and the fido submission was never driven at all).
fn observe_midcall_scrub(
    seen: &Arc<Mutex<Vec<ScrubObservation>>>,
    label: &'static str,
    value: &str,
) {
    let leaked = protonwire_core::redact::scrub(value).as_ref() != value;
    seen.lock().unwrap().push((label, value.to_owned(), leaked));
}

/// The SRP login exchange with mid-call scrub checks at the
/// `/auth/v4/info` step — the first credential-bearing response, served
/// WHILE `begin_login` is blocked on it.
fn srp_login_steps_checked(
    username: &str,
    password: &str,
    scopes: &'static [&'static str],
    tfa: Value,
    midcall: &Arc<Mutex<Vec<ScrubObservation>>>,
) -> Vec<Step> {
    let server = Arc::new(SrpServer::register(username, password));
    let server_for_info = Arc::clone(&server);
    let server_for_auth = Arc::clone(&server);
    let check_user = (Arc::clone(midcall), username.to_owned());
    let check_pass = (Arc::clone(midcall), password.to_owned());
    vec![
        // The anonymous-session mint muon performs before the first
        // send on a credential-less session (spike memo Q2).
        Step::static_json("POST", "/auth/v4/sessions", "200 OK", anon_session()),
        Step::computed("POST", "/auth/v4/info", move |_| {
            // MID-CALL: begin_login is blocked on this response, so its
            // peer-secret handles (or a mutation's registered ones) are
            // live RIGHT NOW — the window the old post-call-only pin
            // could not see into.
            observe_midcall_scrub(&check_user.0, "username", &check_user.1);
            observe_midcall_scrub(&check_pass.0, "password", &check_pass.1);
            let ephemeral = server_for_info.challenge();
            Response::json("200 OK", auth_info("srp-session-1", ephemeral))
        }),
        Step::computed("POST", "/auth/v4", move |recorded| {
            match server_for_auth.verify(recorded) {
                Some(server_proof) => {
                    Response::json("200 OK", auth_v4(server_proof, scopes, tfa.clone()))
                }
                None => Response::error(
                    "400 Bad Request",
                    8002,
                    "incorrect password (real SRP proof verification failed)",
                ),
            }
        }),
    ]
}

/// The 2FA step with mid-call scrub checks — served WHILE
/// `submit_fido_payload` is blocked on it (the M4 survivor fix: the
/// old pin never drove this call at all).
fn two_factor_fido_step_checked(
    client_data: &str,
    authenticator_data: &str,
    signature: &str,
    midcall: &Arc<Mutex<Vec<ScrubObservation>>>,
) -> Step {
    let midcall = Arc::clone(midcall);
    let cd = client_data.to_owned();
    let ad = authenticator_data.to_owned();
    let sig = signature.to_owned();
    Step::computed("POST", "/auth/v4/2fa", move |_| {
        // MID-CALL: submit_fido_payload's assertion handles are live
        // right now.
        observe_midcall_scrub(&midcall, "fido-client-data", &cd);
        observe_midcall_scrub(&midcall, "fido-authenticator-data", &ad);
        observe_midcall_scrub(&midcall, "fido-signature", &sig);
        Response::json("200 OK", json!({"Scopes": ["loggedin", "full"]}))
    })
}

/// The S4 wire path's contract, pinned: every credential-shaped value
/// that arrives through the trait stays OUT of the global scrub registry
/// (peer storage only), while the one secret the adapter MINTS (a fork
/// selector, local provenance) IS registered. A future handler writing
/// `register_secret(peer.expose())` or `SecretString::new(wire_value)`
/// breaks this test.
///
/// Blindness fix (qa P2, mutation-proven M2/M4 survivors): the old pin
/// asserted only AFTER the calls — a mutated registration whose handle
/// dropped at call end was pruned from the registry before the assert
/// ran, and the FIDO submission was never driven at all. Now every
/// credential-bearing call is observed MID-CALL inside its responder
/// step closure (the handle-live window), the fido submission is
/// driven, and the post-call asserts remain for the persistent-guard
/// mutation shape. The S1 flood + local-asset arms are mirrored at the
/// wire seam beside the real exchanges.
#[test]
fn wire_supplied_credentials_never_enter_the_scrub_registry() {
    let username = "peerpin-username-value";
    let password = "peerpin-password-value";
    let fido_client_data = "peerpin-fido-client-data";
    let fido_authenticator_data = "peerpin-fido-authenticator-data";
    let fido_signature = "peerpin-fido-signature";
    let imported_selector = "peerpin-imported-selector";
    let minted_selector = "peerpin-minted-selector";
    let midcall: Arc<Mutex<Vec<ScrubObservation>>> = Arc::new(Mutex::new(Vec::new()));

    // One exchange carrying three credential-bearing calls, every one
    // observed WHILE the adapter is inside the call: begin_login
    // (checked at /auth/v4/info), submit_fido_payload (checked at
    // /auth/v4/2fa), and fork — which mints the LOCAL-provenance asset
    // the flood arm below leans on.
    let (handle, port, _seen) = spawn_scripted(
        srp_login_steps_checked(username, password, &["twofactor"], tfa_fido(), &midcall)
            .into_iter()
            .chain([two_factor_fido_step_checked(
                fido_client_data,
                fido_authenticator_data,
                fido_signature,
                &midcall,
            )])
            .chain([Step::static_json(
                "POST",
                "/auth/v4/sessions/forks",
                "200 OK",
                json!({"Selector": minted_selector}),
            )])
            .collect(),
    );
    let adapter = adapter_on_port(port);
    adapter.begin_login(username, password).expect("login");
    adapter
        .submit_fido_payload(&Fido2Payload {
            client_data: fido_client_data.into(),
            authenticator_data: fido_authenticator_data.into(),
            signature: fido_signature.into(),
            credential_id: FIDO_CREDENTIAL_ID_BYTES.to_vec(),
        })
        .expect("2fa fido");
    let selector = adapter.fork("localagent").expect("fork");
    handle.join().expect("responder thread");
    assert_eq!(selector.as_str(), minted_selector);

    // An imported selector is peer-derived too: a second exchange,
    // observed mid-call at its GET step as well.
    let import_midcall = Arc::clone(&midcall);
    let import_selector_value = imported_selector.to_owned();
    let (handle, port, _seen) = spawn_scripted(vec![Step::computed(
        "GET",
        format!("/auth/v4/sessions/forks/{imported_selector}"),
        move |_| {
            // MID-CALL: import_fork is blocked on this response.
            observe_midcall_scrub(&import_midcall, "imported-selector", &import_selector_value);
            Response::json("200 OK", fork_get_response("forked-uid-2", "forked-user-2"))
        },
    )]);
    let importer = adapter_on_port(port);
    importer
        .import_fork(&ForkSelector::new(imported_selector))
        .expect("import");
    handle.join().expect("responder thread");

    // MID-CALL verdicts — the M2/M4 fix: every observation ran while a
    // mutated registration's handle would have been live, so a
    // peer_secret -> register_secret mutation fails HERE, not after
    // the registry prunes the dropped handle.
    for (label, value, leaked) in midcall.lock().unwrap().iter() {
        assert!(
            !leaked,
            "mid-call ({label}): a wire-supplied credential was registered \
             for scrubbing DURING the call: {value}"
        );
    }

    // POST-CALL defense: the values stayed out of the registry after
    // the calls too (kills the persistent-guard mutation shape, where
    // the handle is kept alive past the call).
    for value in [
        username,
        password,
        fido_client_data,
        fido_authenticator_data,
        fido_signature,
        imported_selector,
    ] {
        assert_eq!(
            protonwire_core::redact::scrub(value),
            value,
            "a wire-supplied credential must never be registered for scrubbing"
        );
    }

    // The minted selector IS registered (local provenance — contrast
    // every peer value above): the adapter's guard keeps it scrubbable
    // for the adapter's lifetime, which is what the flood arm leans on.
    assert_eq!(
        protonwire_core::redact::scrub(minted_selector),
        protonwire_core::redact::REDACTED
    );

    // The S1 flood + local-asset arms (core pins them at the unit;
    // this mirrors both at the wire seam, beside real exchanges): 4096
    // junk values flood the exact front door every wire-supplied
    // credential crosses — none may enter the registry — and the
    // PRE-REGISTERED local asset must stay exactly as scrubbable after
    // the flood as before it (weak-ref registry, no cap to poison).
    let flood: Vec<_> = (0..4096)
        .map(|i| protonwire_core::redact::peer_secret(format!("peerpin-junk-{i:06}")))
        .collect();
    for peer in flood.iter().step_by(256) {
        assert_eq!(
            protonwire_core::redact::scrub(peer.expose()),
            peer.expose(),
            "a flooded peer value must never be registered"
        );
    }
    assert_eq!(
        protonwire_core::redact::scrub(minted_selector),
        protonwire_core::redact::REDACTED,
        "the pre-registered local asset must stay scrubbable after the flood"
    );
}

// ===========================================================================
// The real-Muon canary arm (m2-plan S1/S4): muon's REAL auth code paths
// driven offline with canary values as live credentials
// ===========================================================================

/// A fingerprint provider carrying a canary value (the real
/// `muon::common::auth` "setting fingerprint" site fires during the
/// anonymous-session mint when a provider supplies one).
#[derive(Debug, Clone)]
struct CanaryFingerprint(muon::Fingerprint);

impl muon::ProvideInformation for CanaryFingerprint {
    fn fingerprint(&self) -> Option<muon::Fingerprint> {
        Some(self.0.clone())
    }
}

/// The real-muon emitter. What runs per assertion level — all REAL muon
/// 2.6.1 code, offline, against the loopback responder:
///
/// 1. `Client::builder(..).build()` — the real hyper transport over the
///    real tokio OS/runtime pieces (production `protonwire_api::runtime`).
/// 2. Anonymous-session mint with a fingerprint provider (real
///    `muon::common::auth`: "setting fingerprint {canary}").
/// 3. `Session::auth().login(canary, canary)` — the real SRP login
///    (real `muon::auth::login`: username, SRP session id, uid fields,
///    `%auth` Display; real `muon::store` Auth Debug).
/// 4. `LoginTwoFactorFlow::totp(canary)` — the REAL TOTP-at-info site
///    the PRD's FR-7P claim names, with the canary code as the live
///    credential. (Driven on the flow object directly: the adapter's
///    trait arm refuses non-TOTP-shaped input, and a canary value is
///    deliberately not TOTP-shaped.)
/// 5. `Client::get_session(missing-canary-key)` — the real
///    `muon::client` session-key site.
/// 6. `AuthFlow::from_fork().with_selector(canary)` — the real
///    `muon::auth::from_fork` selector sites (twice at info per the S0
///    memo), as the FR-7L import path.
/// 7. A scripted `Set-Cookie` response header carrying the cookie
///    canary (sec rider, S4 round). PREMISE CORRECTED during landing:
///    at pinned muon 2.6.1 the retry handler's DEBUG site formats the
///    response through `Display` (`received http::Response { status,
///    error_code }` — no headers), so no Set-Cookie value reaches any
///    writer even with the `muon::common::retry` cap removed; the step
///    is therefore an engine-upgrade TRAP, not a currently
///    load-bearing pin — every canary run now pushes a secret-shaped
///    response header through the real transport and the real retry
///    handler, so a future muon that logs response headers (e.g. by
///    switching to `{res:?}`, whose Debug DOES carry the full
///    HeaderMap — res.rs:59-67) turns this arm red at exactly the
///    levels the cap guards. Mutation-verified while landing: with the
///    cap entry neutralized to TRACE the arm stayed green and the
///    captured writer showed the Display shape verbatim.
///
/// Disclosure — the one site NOT driven: pvpnclient's
/// `supervisor::localagent` trace (fork selector + cookies). pvpnclient
/// is a protun transitive and is not linked into this crate's test
/// binary; its site remains covered by the S1 stub arm, which injects
/// every canary class through every site including that one.
///
/// FINDINGS — this arm's first two catches, both UNKNOWN to the S0
/// memo's Q9 table and therefore to the S1 stub arm (the stub can only
/// replay the memo's sites; driving real muon found more):
///
/// 1. `muon::transport::http::req` logs the whole request at `warn`
///    ("is using the default time constraint self=GET
///    /auth/v4/sessions/forks/{selector}") — and the fork selector
///    RIDES THE PATH, so the selector class reaches the writer at
///    EVERY allowed runtime level through a module the S1 caps do not
///    name.
/// 2. `muon::transport::http::hyper::sender` (and its `http1` sibling)
///    log full request objects INCLUDING BODIES at `debug`
///    (`sending request with hyper req=Request { .., body: Body {
///    data: Some(b"{\"TwoFactorCode\":\"...\"}") } }`) — every
///    credential that travels a request body (username, TOTP, FIDO
///    assertions, refresh tokens, the fingerprint payload) leaks at
///    debug/trace.
///
/// Scrubbing cannot cover either site (peer-derived values must never
/// enter the registry), and before-formatting suppression for them
/// lives in `crates/core/src/redact.rs` — the S1 lane's file, not this
/// lane's. RESOLVED: the fix — `("muon::transport", Level::ERROR)` in
/// `MODULE_CAPS` — was validated against this exact arm, reported, and
/// landed by the S1 lane at 29a90b5 (with the stub arm extended to
/// replay both new sites). The arm below runs GREEN at all five levels
/// as the permanent real-muon regression pin; if a future engine
/// upgrade moves a leak outside the capped subtrees, this arm is what
/// catches it.
struct RealMuonCanaryEmitter;

impl protonwire_core::redact::canary::CanaryEmitter for RealMuonCanaryEmitter {
    fn name(&self) -> &'static str {
        "muon-2.6.1"
    }

    fn emit(&self, c: &protonwire_core::redact::canary::Canaries) {
        use muon::auth::LoginFlow;
        use protonwire_api::runtime::TokioOs;
        use protonwire_api::runtime::TokioSpawner;
        use protonwire_api::runtime::os_prng;

        // Owned canary values: the step closures and the single async
        // scope below are 'static.
        let uid = c.uid.clone();
        let session_id = c.session_id.clone();
        let username = c.username.clone();
        let password = c.password.clone();
        let totp = c.totp.clone();
        let selector = c.selector.clone();
        let token = c.token.clone();
        let fingerprint = CanaryFingerprint(muon::Fingerprint(json!({
            "canary": c.fingerprint, "secret": c.private_key,
        })));

        let server = Arc::new(SrpServer::register(&username, &password));
        let server_for_info = Arc::clone(&server);
        let server_for_auth = Arc::clone(&server);
        let auth_uid = uid.clone();
        let auth_token = token.clone();
        let auth_token_refresh = format!("{token}-r");

        let cookie_header = c.cookie.clone();
        let anon_uid = uid.clone();
        let anon_token = token.clone();
        let anon_refresh = format!("{token}-r");

        let mut script = vec![
            // The scripted Set-Cookie step (item 7 above): a real
            // response header carrying the cookie canary through the
            // real transport and the real retry handler on every
            // canary run (see the premise correction — a trap for
            // engines that start logging response headers).
            Step::computed("POST", "/auth/v4/sessions", move |_| {
                let body = serde_json::to_vec(&json!({
                    "UID": anon_uid, "UserID": null,
                    "AccessToken": anon_token, "RefreshToken": anon_refresh,
                    "Scopes": ["unauth"],
                }))
                .expect("serialize scripted body");
                Response {
                    status: "200 OK",
                    headers: vec![
                        ("Content-Type".into(), "application/json".into()),
                        (
                            "Set-Cookie".into(),
                            format!("Session-Id={cookie_header}; Path=/; Secure; HttpOnly"),
                        ),
                    ],
                    body,
                }
            }),
            Step::computed("POST", "/auth/v4/info", move |_| {
                Response::json(
                    "200 OK",
                    json!({
                        "SRPSession": session_id, "Version": 4,
                        "Salt": SRP_SALT, "Modulus": signed_modulus(),
                        "ServerEphemeral": server_for_info.challenge(),
                    }),
                )
            }),
            Step::computed("POST", "/auth/v4", move |recorded| {
                match server_for_auth.verify(recorded) {
                    Some(proof) => Response::json(
                        "200 OK",
                        json!({
                            "ServerProof": proof, "PasswordMode": 1,
                            "UID": auth_uid, "UserID": auth_uid,
                            "AccessToken": auth_token, "RefreshToken": auth_token_refresh,
                            "Scopes": ["twofactor"], "2FA": {"Enabled": 1},
                        }),
                    ),
                    None => Response::error("400 Bad Request", 8002, "canary password rejected"),
                }
            }),
            Step::static_json(
                "POST",
                "/auth/v4/2fa",
                "200 OK",
                json!({"Scopes": ["loggedin", "full"]}),
            ),
        ];
        script.push(Step::static_json(
            "GET",
            format!("/auth/v4/sessions/forks/{selector}"),
            "200 OK",
            json!({
                "Payload": null, "UID": c.session_id, "UserID": c.username,
                "AccessToken": c.token, "RefreshToken": format!("{}-r", c.token),
                "Scopes": ["loggedin"],
            }),
        ));
        let (handle, port, _seen) = spawn_scripted(script);

        let bridge = TokioBridge::dedicated().expect("canary runtime");
        let server_url: muon::common::Server = format!("http://127.0.0.1:{port}/")
            .parse()
            .expect("loopback url");
        let env = muon::Environment::new_custom(LoopbackEnv {
            servers: vec![server_url],
        });
        let app = muon::App::new("linux-vpn@1.0.0").expect("app");
        let store = MemorySessionStore::new();
        let missing_session_key = format!("missing-{}", c.session_id);

        // One async scope owning everything: the REAL client build, the
        // real login with canary credentials, the real 2FA site, the
        // real session-key site, and the real from_fork selector sites.
        bridge.block_on(Box::pin(async move {
            let client = muon::Client::builder(app, env)
                .with_operating_system(TokioOs::default(), os_prng().expect("entropy"))
                .with_multi_thread_executor(TokioSpawner)
                .with_persistence(store)
                .with_info_provider(fingerprint)
                .without_cookie_store()
                .build()
                .expect("canary muon client");

            let session = client
                .new_session_without_credentials("canary".to_owned())
                .await
                .expect("canary session");
            let flow = session.auth().login(&username, &password).await;
            let two_factor = match flow {
                LoginFlow::TwoFactor(flow, _) => flow,
                other => panic!("canary login must reach the 2FA stage, got {other:?}"),
            };
            // The REAL TOTP site with the canary code as the live value.
            let logged_in = two_factor.totp(totp).await.expect("canary 2fa");
            drop(logged_in);

            // The real muon::client session-key site.
            let _ = client.get_session(missing_session_key).await;

            // The real muon::auth::from_fork selector sites.
            let child = client
                .new_session_without_credentials("child".to_owned())
                .await
                .expect("child session");
            let imported = child.auth().from_fork().with_selector(selector).await;
            drop(imported);
        }));

        handle.join().expect("canary responder thread");
    }
}

/// T-32, real arm: every canary class driven through muon's real auth
/// code paths — login, TOTP, store, fingerprint, session keys, and the
/// from_fork selector flow — must reach NO captured writer at ANY
/// allowed runtime level, and the suppressed modules' events must never
/// be formatted at all. Reuses `assert_no_secrets_reach_logs`
/// unchanged (m2-plan S1).
///
/// RED-TO-GREEN HISTORY: this arm first ran red, catching two
/// transport-layer disclosure sites the S0 memo.s Q9 table missed
/// (see the emitter documentation above); the fix — one MODULE_CAPS
/// entry — was validated against this exact arm and landed by the S1
/// lane at 29a90b5 (`("muon::transport", Level::ERROR)`); the arm is
/// green at all five levels since and stays in the suite as the
/// permanent real-muon regression pin.
#[test]
fn t32_real_muon_arm_no_secret_class_reaches_any_writer() {
    protonwire_core::redact::canary::assert_no_secrets_reach_logs(&RealMuonCanaryEmitter);
}
